# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from controller import MurmurRPC_pb2 as MurmurRPC__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in MurmurRPC_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class V1Stub(object):
    """── Service definition ─────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUptime = channel.unary_unary(
                '/MurmurRPC.V1/GetUptime',
                request_serializer=MurmurRPC__pb2.Void.SerializeToString,
                response_deserializer=MurmurRPC__pb2.Uptime.FromString,
                _registered_method=True)
        self.GetVersion = channel.unary_unary(
                '/MurmurRPC.V1/GetVersion',
                request_serializer=MurmurRPC__pb2.Void.SerializeToString,
                response_deserializer=MurmurRPC__pb2.Version.FromString,
                _registered_method=True)
        self.Events = channel.unary_stream(
                '/MurmurRPC.V1/Events',
                request_serializer=MurmurRPC__pb2.Void.SerializeToString,
                response_deserializer=MurmurRPC__pb2.Event.FromString,
                _registered_method=True)
        self.ServerCreate = channel.unary_unary(
                '/MurmurRPC.V1/ServerCreate',
                request_serializer=MurmurRPC__pb2.Void.SerializeToString,
                response_deserializer=MurmurRPC__pb2.Server.FromString,
                _registered_method=True)
        self.ServerQuery = channel.unary_unary(
                '/MurmurRPC.V1/ServerQuery',
                request_serializer=MurmurRPC__pb2.Void.SerializeToString,
                response_deserializer=MurmurRPC__pb2.Server_List.FromString,
                _registered_method=True)
        self.ServerGet = channel.unary_unary(
                '/MurmurRPC.V1/ServerGet',
                request_serializer=MurmurRPC__pb2.Server.SerializeToString,
                response_deserializer=MurmurRPC__pb2.Server.FromString,
                _registered_method=True)
        self.ServerStart = channel.unary_unary(
                '/MurmurRPC.V1/ServerStart',
                request_serializer=MurmurRPC__pb2.Server.SerializeToString,
                response_deserializer=MurmurRPC__pb2.Void.FromString,
                _registered_method=True)
        self.ServerStop = channel.unary_unary(
                '/MurmurRPC.V1/ServerStop',
                request_serializer=MurmurRPC__pb2.Server.SerializeToString,
                response_deserializer=MurmurRPC__pb2.Void.FromString,
                _registered_method=True)
        self.ServerRemove = channel.unary_unary(
                '/MurmurRPC.V1/ServerRemove',
                request_serializer=MurmurRPC__pb2.Server.SerializeToString,
                response_deserializer=MurmurRPC__pb2.Void.FromString,
                _registered_method=True)
        self.ServerEvents = channel.unary_stream(
                '/MurmurRPC.V1/ServerEvents',
                request_serializer=MurmurRPC__pb2.Server.SerializeToString,
                response_deserializer=MurmurRPC__pb2.Event.FromString,
                _registered_method=True)
        self.GetAllChannels = channel.unary_unary(
                '/MurmurRPC.V1/GetAllChannels',
                request_serializer=MurmurRPC__pb2.Server.SerializeToString,
                response_deserializer=MurmurRPC__pb2.Channel_List.FromString,
                _registered_method=True)
        self.ChannelGet = channel.unary_unary(
                '/MurmurRPC.V1/ChannelGet',
                request_serializer=MurmurRPC__pb2.Channel.SerializeToString,
                response_deserializer=MurmurRPC__pb2.Channel.FromString,
                _registered_method=True)
        self.ChannelAdd = channel.unary_unary(
                '/MurmurRPC.V1/ChannelAdd',
                request_serializer=MurmurRPC__pb2.Channel.SerializeToString,
                response_deserializer=MurmurRPC__pb2.Channel.FromString,
                _registered_method=True)
        self.ChannelRemove = channel.unary_unary(
                '/MurmurRPC.V1/ChannelRemove',
                request_serializer=MurmurRPC__pb2.Channel.SerializeToString,
                response_deserializer=MurmurRPC__pb2.Void.FromString,
                _registered_method=True)
        self.ChannelUpdate = channel.unary_unary(
                '/MurmurRPC.V1/ChannelUpdate',
                request_serializer=MurmurRPC__pb2.Channel.SerializeToString,
                response_deserializer=MurmurRPC__pb2.Channel.FromString,
                _registered_method=True)
        self.ChannelQuery = channel.unary_unary(
                '/MurmurRPC.V1/ChannelQuery',
                request_serializer=MurmurRPC__pb2.Channel.SerializeToString,
                response_deserializer=MurmurRPC__pb2.Channel_List.FromString,
                _registered_method=True)
        self.GetAllUsers = channel.unary_unary(
                '/MurmurRPC.V1/GetAllUsers',
                request_serializer=MurmurRPC__pb2.Server.SerializeToString,
                response_deserializer=MurmurRPC__pb2.User_List.FromString,
                _registered_method=True)
        self.UserGet = channel.unary_unary(
                '/MurmurRPC.V1/UserGet',
                request_serializer=MurmurRPC__pb2.User.SerializeToString,
                response_deserializer=MurmurRPC__pb2.User.FromString,
                _registered_method=True)
        self.UserUpdate = channel.unary_unary(
                '/MurmurRPC.V1/UserUpdate',
                request_serializer=MurmurRPC__pb2.User.SerializeToString,
                response_deserializer=MurmurRPC__pb2.User.FromString,
                _registered_method=True)
        self.UserKick = channel.unary_unary(
                '/MurmurRPC.V1/UserKick',
                request_serializer=MurmurRPC__pb2.User_KickBan.SerializeToString,
                response_deserializer=MurmurRPC__pb2.Void.FromString,
                _registered_method=True)
        self.GetTree = channel.unary_unary(
                '/MurmurRPC.V1/GetTree',
                request_serializer=MurmurRPC__pb2.Server.SerializeToString,
                response_deserializer=MurmurRPC__pb2.Tree.FromString,
                _registered_method=True)
        self.SendMessage = channel.unary_unary(
                '/MurmurRPC.V1/SendMessage',
                request_serializer=MurmurRPC__pb2.TextMessage.SerializeToString,
                response_deserializer=MurmurRPC__pb2.Void.FromString,
                _registered_method=True)
        self.GetBans = channel.unary_unary(
                '/MurmurRPC.V1/GetBans',
                request_serializer=MurmurRPC__pb2.Server.SerializeToString,
                response_deserializer=MurmurRPC__pb2.Ban_List.FromString,
                _registered_method=True)
        self.SetBans = channel.unary_unary(
                '/MurmurRPC.V1/SetBans',
                request_serializer=MurmurRPC__pb2.Ban_List.SerializeToString,
                response_deserializer=MurmurRPC__pb2.Void.FromString,
                _registered_method=True)
        self.GetLogs = channel.unary_unary(
                '/MurmurRPC.V1/GetLogs',
                request_serializer=MurmurRPC__pb2.Log.SerializeToString,
                response_deserializer=MurmurRPC__pb2.Log_List.FromString,
                _registered_method=True)
        self.GetConfig = channel.unary_unary(
                '/MurmurRPC.V1/GetConfig',
                request_serializer=MurmurRPC__pb2.Server.SerializeToString,
                response_deserializer=MurmurRPC__pb2.Config_List.FromString,
                _registered_method=True)
        self.GetConfigField = channel.unary_unary(
                '/MurmurRPC.V1/GetConfigField',
                request_serializer=MurmurRPC__pb2.Config.SerializeToString,
                response_deserializer=MurmurRPC__pb2.Config.FromString,
                _registered_method=True)
        self.SetConfigField = channel.unary_unary(
                '/MurmurRPC.V1/SetConfigField',
                request_serializer=MurmurRPC__pb2.Config.SerializeToString,
                response_deserializer=MurmurRPC__pb2.Void.FromString,
                _registered_method=True)
        self.ResetConfigField = channel.unary_unary(
                '/MurmurRPC.V1/ResetConfigField',
                request_serializer=MurmurRPC__pb2.Config.SerializeToString,
                response_deserializer=MurmurRPC__pb2.Void.FromString,
                _registered_method=True)
        self.GetUsers = channel.unary_unary(
                '/MurmurRPC.V1/GetUsers',
                request_serializer=MurmurRPC__pb2.Server.SerializeToString,
                response_deserializer=MurmurRPC__pb2.User_List.FromString,
                _registered_method=True)
        self.GetDatabaseUsers = channel.unary_unary(
                '/MurmurRPC.V1/GetDatabaseUsers',
                request_serializer=MurmurRPC__pb2.Server.SerializeToString,
                response_deserializer=MurmurRPC__pb2.Database_User_List.FromString,
                _registered_method=True)
        self.GetDatabaseUser = channel.unary_unary(
                '/MurmurRPC.V1/GetDatabaseUser',
                request_serializer=MurmurRPC__pb2.Database_User.SerializeToString,
                response_deserializer=MurmurRPC__pb2.Database_User.FromString,
                _registered_method=True)
        self.UpdateDatabaseUser = channel.unary_unary(
                '/MurmurRPC.V1/UpdateDatabaseUser',
                request_serializer=MurmurRPC__pb2.Database_User.SerializeToString,
                response_deserializer=MurmurRPC__pb2.Void.FromString,
                _registered_method=True)
        self.RegisterDatabaseUser = channel.unary_unary(
                '/MurmurRPC.V1/RegisterDatabaseUser',
                request_serializer=MurmurRPC__pb2.Database_User.SerializeToString,
                response_deserializer=MurmurRPC__pb2.Database_User.FromString,
                _registered_method=True)
        self.DeregisterDatabaseUser = channel.unary_unary(
                '/MurmurRPC.V1/DeregisterDatabaseUser',
                request_serializer=MurmurRPC__pb2.Database_User.SerializeToString,
                response_deserializer=MurmurRPC__pb2.Void.FromString,
                _registered_method=True)
        self.VerifyPassword = channel.unary_unary(
                '/MurmurRPC.V1/VerifyPassword',
                request_serializer=MurmurRPC__pb2.Database_User.SerializeToString,
                response_deserializer=MurmurRPC__pb2.Database_User.FromString,
                _registered_method=True)
        self.FindDatabaseUser = channel.unary_unary(
                '/MurmurRPC.V1/FindDatabaseUser',
                request_serializer=MurmurRPC__pb2.Database_User.SerializeToString,
                response_deserializer=MurmurRPC__pb2.Database_User.FromString,
                _registered_method=True)


class V1Servicer(object):
    """── Service definition ─────────────────────────────────────────────────────

    """

    def GetUptime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Events(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerCreate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerGet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerStart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerStop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerRemove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllChannels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChannelGet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChannelAdd(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChannelRemove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChannelUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChannelQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UserGet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UserUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UserKick(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTree(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBans(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetBans(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfigField(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetConfigField(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetConfigField(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDatabaseUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDatabaseUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDatabaseUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterDatabaseUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeregisterDatabaseUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyPassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindDatabaseUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_V1Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUptime': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUptime,
                    request_deserializer=MurmurRPC__pb2.Void.FromString,
                    response_serializer=MurmurRPC__pb2.Uptime.SerializeToString,
            ),
            'GetVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersion,
                    request_deserializer=MurmurRPC__pb2.Void.FromString,
                    response_serializer=MurmurRPC__pb2.Version.SerializeToString,
            ),
            'Events': grpc.unary_stream_rpc_method_handler(
                    servicer.Events,
                    request_deserializer=MurmurRPC__pb2.Void.FromString,
                    response_serializer=MurmurRPC__pb2.Event.SerializeToString,
            ),
            'ServerCreate': grpc.unary_unary_rpc_method_handler(
                    servicer.ServerCreate,
                    request_deserializer=MurmurRPC__pb2.Void.FromString,
                    response_serializer=MurmurRPC__pb2.Server.SerializeToString,
            ),
            'ServerQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.ServerQuery,
                    request_deserializer=MurmurRPC__pb2.Void.FromString,
                    response_serializer=MurmurRPC__pb2.Server_List.SerializeToString,
            ),
            'ServerGet': grpc.unary_unary_rpc_method_handler(
                    servicer.ServerGet,
                    request_deserializer=MurmurRPC__pb2.Server.FromString,
                    response_serializer=MurmurRPC__pb2.Server.SerializeToString,
            ),
            'ServerStart': grpc.unary_unary_rpc_method_handler(
                    servicer.ServerStart,
                    request_deserializer=MurmurRPC__pb2.Server.FromString,
                    response_serializer=MurmurRPC__pb2.Void.SerializeToString,
            ),
            'ServerStop': grpc.unary_unary_rpc_method_handler(
                    servicer.ServerStop,
                    request_deserializer=MurmurRPC__pb2.Server.FromString,
                    response_serializer=MurmurRPC__pb2.Void.SerializeToString,
            ),
            'ServerRemove': grpc.unary_unary_rpc_method_handler(
                    servicer.ServerRemove,
                    request_deserializer=MurmurRPC__pb2.Server.FromString,
                    response_serializer=MurmurRPC__pb2.Void.SerializeToString,
            ),
            'ServerEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.ServerEvents,
                    request_deserializer=MurmurRPC__pb2.Server.FromString,
                    response_serializer=MurmurRPC__pb2.Event.SerializeToString,
            ),
            'GetAllChannels': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllChannels,
                    request_deserializer=MurmurRPC__pb2.Server.FromString,
                    response_serializer=MurmurRPC__pb2.Channel_List.SerializeToString,
            ),
            'ChannelGet': grpc.unary_unary_rpc_method_handler(
                    servicer.ChannelGet,
                    request_deserializer=MurmurRPC__pb2.Channel.FromString,
                    response_serializer=MurmurRPC__pb2.Channel.SerializeToString,
            ),
            'ChannelAdd': grpc.unary_unary_rpc_method_handler(
                    servicer.ChannelAdd,
                    request_deserializer=MurmurRPC__pb2.Channel.FromString,
                    response_serializer=MurmurRPC__pb2.Channel.SerializeToString,
            ),
            'ChannelRemove': grpc.unary_unary_rpc_method_handler(
                    servicer.ChannelRemove,
                    request_deserializer=MurmurRPC__pb2.Channel.FromString,
                    response_serializer=MurmurRPC__pb2.Void.SerializeToString,
            ),
            'ChannelUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.ChannelUpdate,
                    request_deserializer=MurmurRPC__pb2.Channel.FromString,
                    response_serializer=MurmurRPC__pb2.Channel.SerializeToString,
            ),
            'ChannelQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.ChannelQuery,
                    request_deserializer=MurmurRPC__pb2.Channel.FromString,
                    response_serializer=MurmurRPC__pb2.Channel_List.SerializeToString,
            ),
            'GetAllUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllUsers,
                    request_deserializer=MurmurRPC__pb2.Server.FromString,
                    response_serializer=MurmurRPC__pb2.User_List.SerializeToString,
            ),
            'UserGet': grpc.unary_unary_rpc_method_handler(
                    servicer.UserGet,
                    request_deserializer=MurmurRPC__pb2.User.FromString,
                    response_serializer=MurmurRPC__pb2.User.SerializeToString,
            ),
            'UserUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.UserUpdate,
                    request_deserializer=MurmurRPC__pb2.User.FromString,
                    response_serializer=MurmurRPC__pb2.User.SerializeToString,
            ),
            'UserKick': grpc.unary_unary_rpc_method_handler(
                    servicer.UserKick,
                    request_deserializer=MurmurRPC__pb2.User_KickBan.FromString,
                    response_serializer=MurmurRPC__pb2.Void.SerializeToString,
            ),
            'GetTree': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTree,
                    request_deserializer=MurmurRPC__pb2.Server.FromString,
                    response_serializer=MurmurRPC__pb2.Tree.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=MurmurRPC__pb2.TextMessage.FromString,
                    response_serializer=MurmurRPC__pb2.Void.SerializeToString,
            ),
            'GetBans': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBans,
                    request_deserializer=MurmurRPC__pb2.Server.FromString,
                    response_serializer=MurmurRPC__pb2.Ban_List.SerializeToString,
            ),
            'SetBans': grpc.unary_unary_rpc_method_handler(
                    servicer.SetBans,
                    request_deserializer=MurmurRPC__pb2.Ban_List.FromString,
                    response_serializer=MurmurRPC__pb2.Void.SerializeToString,
            ),
            'GetLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLogs,
                    request_deserializer=MurmurRPC__pb2.Log.FromString,
                    response_serializer=MurmurRPC__pb2.Log_List.SerializeToString,
            ),
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=MurmurRPC__pb2.Server.FromString,
                    response_serializer=MurmurRPC__pb2.Config_List.SerializeToString,
            ),
            'GetConfigField': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfigField,
                    request_deserializer=MurmurRPC__pb2.Config.FromString,
                    response_serializer=MurmurRPC__pb2.Config.SerializeToString,
            ),
            'SetConfigField': grpc.unary_unary_rpc_method_handler(
                    servicer.SetConfigField,
                    request_deserializer=MurmurRPC__pb2.Config.FromString,
                    response_serializer=MurmurRPC__pb2.Void.SerializeToString,
            ),
            'ResetConfigField': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetConfigField,
                    request_deserializer=MurmurRPC__pb2.Config.FromString,
                    response_serializer=MurmurRPC__pb2.Void.SerializeToString,
            ),
            'GetUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsers,
                    request_deserializer=MurmurRPC__pb2.Server.FromString,
                    response_serializer=MurmurRPC__pb2.User_List.SerializeToString,
            ),
            'GetDatabaseUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDatabaseUsers,
                    request_deserializer=MurmurRPC__pb2.Server.FromString,
                    response_serializer=MurmurRPC__pb2.Database_User_List.SerializeToString,
            ),
            'GetDatabaseUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDatabaseUser,
                    request_deserializer=MurmurRPC__pb2.Database_User.FromString,
                    response_serializer=MurmurRPC__pb2.Database_User.SerializeToString,
            ),
            'UpdateDatabaseUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDatabaseUser,
                    request_deserializer=MurmurRPC__pb2.Database_User.FromString,
                    response_serializer=MurmurRPC__pb2.Void.SerializeToString,
            ),
            'RegisterDatabaseUser': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterDatabaseUser,
                    request_deserializer=MurmurRPC__pb2.Database_User.FromString,
                    response_serializer=MurmurRPC__pb2.Database_User.SerializeToString,
            ),
            'DeregisterDatabaseUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeregisterDatabaseUser,
                    request_deserializer=MurmurRPC__pb2.Database_User.FromString,
                    response_serializer=MurmurRPC__pb2.Void.SerializeToString,
            ),
            'VerifyPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyPassword,
                    request_deserializer=MurmurRPC__pb2.Database_User.FromString,
                    response_serializer=MurmurRPC__pb2.Database_User.SerializeToString,
            ),
            'FindDatabaseUser': grpc.unary_unary_rpc_method_handler(
                    servicer.FindDatabaseUser,
                    request_deserializer=MurmurRPC__pb2.Database_User.FromString,
                    response_serializer=MurmurRPC__pb2.Database_User.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MurmurRPC.V1', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('MurmurRPC.V1', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class V1(object):
    """── Service definition ─────────────────────────────────────────────────────

    """

    @staticmethod
    def GetUptime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MurmurRPC.V1/GetUptime',
            MurmurRPC__pb2.Void.SerializeToString,
            MurmurRPC__pb2.Uptime.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MurmurRPC.V1/GetVersion',
            MurmurRPC__pb2.Void.SerializeToString,
            MurmurRPC__pb2.Version.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Events(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/MurmurRPC.V1/Events',
            MurmurRPC__pb2.Void.SerializeToString,
            MurmurRPC__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ServerCreate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MurmurRPC.V1/ServerCreate',
            MurmurRPC__pb2.Void.SerializeToString,
            MurmurRPC__pb2.Server.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ServerQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MurmurRPC.V1/ServerQuery',
            MurmurRPC__pb2.Void.SerializeToString,
            MurmurRPC__pb2.Server_List.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ServerGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MurmurRPC.V1/ServerGet',
            MurmurRPC__pb2.Server.SerializeToString,
            MurmurRPC__pb2.Server.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ServerStart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MurmurRPC.V1/ServerStart',
            MurmurRPC__pb2.Server.SerializeToString,
            MurmurRPC__pb2.Void.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ServerStop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MurmurRPC.V1/ServerStop',
            MurmurRPC__pb2.Server.SerializeToString,
            MurmurRPC__pb2.Void.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ServerRemove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MurmurRPC.V1/ServerRemove',
            MurmurRPC__pb2.Server.SerializeToString,
            MurmurRPC__pb2.Void.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ServerEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/MurmurRPC.V1/ServerEvents',
            MurmurRPC__pb2.Server.SerializeToString,
            MurmurRPC__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllChannels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MurmurRPC.V1/GetAllChannels',
            MurmurRPC__pb2.Server.SerializeToString,
            MurmurRPC__pb2.Channel_List.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChannelGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MurmurRPC.V1/ChannelGet',
            MurmurRPC__pb2.Channel.SerializeToString,
            MurmurRPC__pb2.Channel.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChannelAdd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MurmurRPC.V1/ChannelAdd',
            MurmurRPC__pb2.Channel.SerializeToString,
            MurmurRPC__pb2.Channel.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChannelRemove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MurmurRPC.V1/ChannelRemove',
            MurmurRPC__pb2.Channel.SerializeToString,
            MurmurRPC__pb2.Void.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChannelUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MurmurRPC.V1/ChannelUpdate',
            MurmurRPC__pb2.Channel.SerializeToString,
            MurmurRPC__pb2.Channel.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChannelQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MurmurRPC.V1/ChannelQuery',
            MurmurRPC__pb2.Channel.SerializeToString,
            MurmurRPC__pb2.Channel_List.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MurmurRPC.V1/GetAllUsers',
            MurmurRPC__pb2.Server.SerializeToString,
            MurmurRPC__pb2.User_List.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UserGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MurmurRPC.V1/UserGet',
            MurmurRPC__pb2.User.SerializeToString,
            MurmurRPC__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UserUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MurmurRPC.V1/UserUpdate',
            MurmurRPC__pb2.User.SerializeToString,
            MurmurRPC__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UserKick(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MurmurRPC.V1/UserKick',
            MurmurRPC__pb2.User_KickBan.SerializeToString,
            MurmurRPC__pb2.Void.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MurmurRPC.V1/GetTree',
            MurmurRPC__pb2.Server.SerializeToString,
            MurmurRPC__pb2.Tree.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MurmurRPC.V1/SendMessage',
            MurmurRPC__pb2.TextMessage.SerializeToString,
            MurmurRPC__pb2.Void.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBans(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MurmurRPC.V1/GetBans',
            MurmurRPC__pb2.Server.SerializeToString,
            MurmurRPC__pb2.Ban_List.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetBans(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MurmurRPC.V1/SetBans',
            MurmurRPC__pb2.Ban_List.SerializeToString,
            MurmurRPC__pb2.Void.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MurmurRPC.V1/GetLogs',
            MurmurRPC__pb2.Log.SerializeToString,
            MurmurRPC__pb2.Log_List.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MurmurRPC.V1/GetConfig',
            MurmurRPC__pb2.Server.SerializeToString,
            MurmurRPC__pb2.Config_List.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConfigField(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MurmurRPC.V1/GetConfigField',
            MurmurRPC__pb2.Config.SerializeToString,
            MurmurRPC__pb2.Config.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetConfigField(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MurmurRPC.V1/SetConfigField',
            MurmurRPC__pb2.Config.SerializeToString,
            MurmurRPC__pb2.Void.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetConfigField(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MurmurRPC.V1/ResetConfigField',
            MurmurRPC__pb2.Config.SerializeToString,
            MurmurRPC__pb2.Void.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MurmurRPC.V1/GetUsers',
            MurmurRPC__pb2.Server.SerializeToString,
            MurmurRPC__pb2.User_List.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDatabaseUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MurmurRPC.V1/GetDatabaseUsers',
            MurmurRPC__pb2.Server.SerializeToString,
            MurmurRPC__pb2.Database_User_List.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDatabaseUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MurmurRPC.V1/GetDatabaseUser',
            MurmurRPC__pb2.Database_User.SerializeToString,
            MurmurRPC__pb2.Database_User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateDatabaseUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MurmurRPC.V1/UpdateDatabaseUser',
            MurmurRPC__pb2.Database_User.SerializeToString,
            MurmurRPC__pb2.Void.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterDatabaseUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MurmurRPC.V1/RegisterDatabaseUser',
            MurmurRPC__pb2.Database_User.SerializeToString,
            MurmurRPC__pb2.Database_User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeregisterDatabaseUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MurmurRPC.V1/DeregisterDatabaseUser',
            MurmurRPC__pb2.Database_User.SerializeToString,
            MurmurRPC__pb2.Void.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MurmurRPC.V1/VerifyPassword',
            MurmurRPC__pb2.Database_User.SerializeToString,
            MurmurRPC__pb2.Database_User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindDatabaseUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MurmurRPC.V1/FindDatabaseUser',
            MurmurRPC__pb2.Database_User.SerializeToString,
            MurmurRPC__pb2.Database_User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
